spring:
    application:
        name: spring-ai-rag-expert
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            embedding:
                options:
                    model: text-embedding-3-small
            chat:
                options:
                    model: gpt-4-turbo
        vectorstore:
            milvus:
                client:
                    host: "localhost"
                    port: 19530
                    username: "root"
                    password: "milvus"
                databaseName: "default"
                collectionName: "vector_store"
                embeddingDimension: 1536
                indexType: IVF_FLAT
                metricType: COSINE

sfg:
    ai-app:
        vectorStorePath: /tmp/vector-store.json
        documentsToLoad:
            - classpath:/cv.json
            - classpath:/vacancies.txt